### ISSUE TITLE
The game is too easy

### ISSUE THREAD

**Issue by oh64** [Bryankaveen/Pokemon-83-Premium#10]
The game is too easy ;
After testing the game, I quickly realized that by pressing ENTER it becomes very easy to "speedrun" the game because the game checking the player's life only after the player is attacked ;
Moreover by typing 99999->P it will give 99999 lives to the player !
**The game should save all data somewhere other than variables.**

**Comment by bryanthrmn** [comment]
In fact, in beta 3, we are going to archive all data; players won't be able (or maybe) to change game data.
Thus, we are going to set limits on health points (HP), Attack (ATK), and defense.
So, no worries; this bug is going to be resolved.

**Comment by oh64** [comment]
Great, can I help you with this?
And there is also a level limit (100 as in the real game)

**Comment by bryanthrmn** [comment]
Let's keep 14 levels at the moment.
You could help by adding "archive LPSA", "unarchive LPSA" etc... (do a pull request so that I can check).
