### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by bryanthrmn** [Bryankaveen/Pokemon-83-Premium#11]
Website should be like this : 
https://betaprofiles.com/?__cf_chl_f_tk=82K_0LJzrnLMsya58sgft1lP6lxqPqX1LmjWuUyMWl4-1642257928-0-gaNycGzNCH0

**Comment by oh64** [comment]
I working on it !
But I prefer to do it on vscode so it's not live

>(translated by Google translation)
