### ISSUE TITLE
Build up game with matrix

### ISSUE THREAD

**Issue by bryanthrmn** [Bryankaveen/Pokemon-83-Premium#12]
I think that matrix will be easier for us to collect game data.
However, a matrix can be used on other programs, which might break our game. 
That's why we are going to keep our customized list with temporary data on the matrix.
What do you guys think ?
Should we avoid using many lists?

**Comment by oh64** [comment]
I think it's better to use save lists and archive them after.

for the variables :
    open :
1->dim(LPOKES
LPOKES(1->A
    save :
{A->LPOKES

For lists :
   open :
LPOKES->L1
   save :
{L1->LPOKES

**Comment by bryanthrmn** [comment]
Yeah, I guess you're right.
Matrix is taking much more space {x,y}>dim([A]) / Output [A](x,y) etc...
Lists are maybe better.

**Comment by oh64** [comment]
Just... The game is impossible?
I start : 
I find myself against a pokemon with 300PV and which does 200 damage !!!!!!!!
While my pokemon only has 50PV (Not exactly but still !!!!)
0XP after 20 minutes of play.
> Translated by Google translate

**Comment by bryanthrmn** [comment]
Yeah we need balance changes actually 😅
Enemies are too OP (Some of them)
At the moment, you'll need to run away from the battle.
I'll make the changes as soon as possible, to make a better matchmaking 😉
