### ISSUE TITLE
Multi-Language support

### ISSUE THREAD

**Issue by notSam25** [Bryankaveen/Pokemon-83-Premium#13]
As I don't speak Spanish would it be possible for implementation of the English language.

**Comment by bryanthrmn** [comment]
Of course, we are working on it. ;)
We already have an English version of the game; check out our latest
English version; Pokemon 83 Beta 2 (1.7)
In fact, Beta 3 will definitively have bigger/better features. Beta 2, may sounds
boring, but don't worry :)

Here is our English web page; https://square-programming.github.io/Pokemon-83-Premium/indexen.html
PS: we don't speak Spanish, we are speaking french. :)

**Comment by notSam25** [comment]
thanks :+1:
