### ISSUE TITLE
Création d'un dictionnaire

### ISSUE THREAD

**Issue by bryanthrmn** [Bryankaveen/Pokemon-83-Premium#3]
Nous aurons besoin de @Capysquid , auteur du jeu, de créer un dictionnaire qui donne les informations liées à chaque label. En effet, la version 1.8 connaît quelques rangement ; il vaut mieux prendre de l'avance.

@Capysquid rends toi dans le code, et complète le dictionnaire (Pokémon-83-Premium/src/LABEL DICTIONNARY)

**Comment by Capysquid** [comment]
Salut,
Je préfère m’excuser d’avance mais j’ai perdu ma calculatrice depuis déjà 5
jours 😞,
Donc je ne pourrais pas avancer davantage tant que je ne la retrouve pas,
Mais la mise à jour de la forêt et déjà prête... Mais dans ma calculatrice
😅
Au revoir.
