### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by bryanthrmn** [Bryankaveen/Pokemon-83-Premium#8]
Need to link this repo to a Github page. Does anyone know how to build an HTML webpage (Github page)?

**Comment by bryanthrmn** [comment]
Maybe we should build a general GitHub site (instead of doing one site per repo)

**Comment by TIny-Hacker** [comment]
> Maybe we should build a general GitHub site (instead of doing one site per repo)

I think that would be a good idea, though having separate project pages also seems like something that might be nice.

**Comment by Capysquid** [comment]
laisse tomber, je n'ai pas respecté l'accord du copyrigth, c'est mort

**Comment by bryanthrmn** [comment]
> laisse tomber, je n'ai pas respecté l'accord du copyrigth, c'est mort

Que veux tu dire par là ? On a recrée le jeu nous-même.

**Comment by Oh64** [comment]
![Uploading IMG20220107201043.jpg…]()

Version béta de Pokémon 83

**Comment by Oh64** [comment]
Ce ne serait pas mieux  ?
Car il ne vient pas de KENSHI ou autre.

**Comment by Capysquid** [comment]
Vous savez qu’il peut me poursuivre en justice ?
C’est mon choix et non le vôtre.
Je changerai mon avis uniquement si Kenshi_Corporation me donne son feu
vert.
En tout cas, je lui laisse une semaine.
La loi, c’est la loi, et si on l’enfreint, on devient un délinquant.
Et en devenir un ne m’intéresse pas du tout.
Si vous avancez trop loin dans se projet et que Kenshi_Corporation se
pointe un jour,
Toutes les charges seront contre moi.
Depuis hier, je n’ai pas l’esprit tranquille.
Alors s’il te plaît Shadow, laisse tomber...
Merci

Au revoir

-Capysquid

**Comment by critor** [comment]
Bonjour Capysquid.


J'ai beaucoup de mal à comprendre le problème. Le jeu original pour TI-82 Stats a apparemment été publié sous licence CC 2.0 BY-SA :
https://tiplanet.org/forum/archives_voir.php?id=2788274

Cette licence très permissive t'autorise entre autres à adapter / modifier / transformer l'œuvre originale :
https://creativecommons.org/licenses/by-sa/2.0/fr/


En te remerciant pour ta lecture et dans l'attente de te lire.

**Comment by bryanthrmn** [comment]
Problème résolu : il faut simplement changer la license.

**Comment by critor** [comment]
La licence CC 2.0 BY-SA n'implique que 2 contraintes :
- BY : mentionner l'auteur du projet original dans les œuvres dérivées
- SA : distribuer les œuvres dérivées dans les mêmes conditions de licence, soit la CC 2.0 BY-SA
https://creativecommons.org/licenses/by-sa/2.0/fr/

Il n'y a que ce dernier point que vous ne respectez pas encore et qui est donc à corriger.

Merci.

**Comment by Capysquid** [comment]
D’accord...
Je comprends.
Je ne sais pas vraiment quoi dire.
J’espère que Shadow n’a pas supprimé ce qu’il avait fait :(
Il va être furax.
En tout cas, merci de m’avoir prévenu.

Au revoir

-Capysquid

**Comment by bryanthrmn** [comment]
> La licence CC 2.0 BY-SA n'implique que 2 contraintes :
> 
> * BY : mentionner l'auteur du projet original dans les œuvres dérivées
> * SA : distribuer les œuvres dérivées dans les mêmes conditions de licence, soit la CC 2.0 BY-SA
>   https://creativecommons.org/licenses/by-sa/2.0/fr/
> 
> Il n'y a que ce dernier point que vous ne respectez pas encore et qui est donc à corriger.
> 
> Merci.

Est-ce qu'il y aurait une version [EN] de la license ? Histoire de publier le texte sur ce repo (il n'est pas dans la liste des licenses)

**Comment by critor** [comment]
Bien sûr :
https://creativecommons.org/licenses/by-sa/2.0/
